[colors.bright]
black = "#475258"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.normal]
black = "#414b50"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.primary]
background = "#272e33"
foreground = "#d3c6aa"

[cursor]
blink_interval = 400

[cursor.style]
blinking="Always"
shape="Block"

[font]
size = 11

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[shell]
program = "/usr/local/bin/bash"

[window]
opacity = 1

# [schemes.everforest_dark_hard.bright]
# black = "#475258"
# blue = "#7fbbb3"
# cyan = "#83c092"
# green = "#a7c080"
# magenta = "#d699b6"
# red = "#e67e80"
# white = "#d3c6aa"
# yellow = "#dbbc7f"
# 
# [schemes.everforest_dark_hard.normal]
# black = "#414b50"
# blue = "#7fbbb3"
# cyan = "#83c092"
# green = "#a7c080"
# magenta = "#d699b6"
# red = "#e67e80"
# white = "#d3c6aa"
# yellow = "#dbbc7f"
# 
# [schemes.everforest_dark_hard.primary]
# background = "#272e33"
# foreground = "#d3c6aa"
# 
# [schemes.everforest_dark_medium.bright]
# black = "#475258"
# blue = "#7fbbb3"
# cyan = "#83c092"
# green = "#a7c080"
# magenta = "#d699b6"
# red = "#e67e80"
# white = "#d3c6aa"
# yellow = "#dbbc7f"
# 
# [schemes.everforest_dark_medium.normal]
# black = "#475258"
# blue = "#7fbbb3"
# cyan = "#83c092"
# green = "#a7c080"
# magenta = "#d699b6"
# red = "#e67e80"
# white = "#d3c6aa"
# yellow = "#dbbc7f"
# 
# [schemes.everforest_dark_medium.primary]
# background = "#2d353b"
# foreground = "#d3c6aa"
# 
# [schemes.nord.bright]
# black = "#4c566a"
# blue = "#81a1c1"
# cyan = "#8fbcbb"
# green = "#a3be8c"
# magenta = "#b48ead"
# red = "#bf616a"
# white = "#eceff4"
# yellow = "#ebcb8b"
# 
# [schemes.nord.cursor]
# cursor = "#d8dee9"
# text = "#2e3440"
# 
# [schemes.nord.dim]
# black = "#373e4d"
# blue = "#68809a"
# cyan = "#6d96a5"
# green = "#809575"
# magenta = "#8c738c"
# red = "#94545d"
# white = "#aeb3bb"
# yellow = "#b29e75"
# 
# [schemes.nord.gruvbox.bright]
# black = "#928374"
# blue = "#83a598"
# cyan = "#8ec07c"
# green = "#b8bb26"
# magenta = "#d3869b"
# red = "#fb4934"
# white = "#ebdbb2"
# yellow = "#fabd2f"
# 
# [schemes.nord.gruvbox.cursor]
# cursor = "CellForeground"
# text = "CellBackground"
# 
# [schemes.nord.gruvbox.dim]
# black = "#32302f"
# blue = "#076678"
# cyan = "#427b58"
# green = "#79740e"
# magenta = "#8f3f71"
# red = "#9d0006"
# white = "#928374"
# yellow = "#b57614"
# 
# [schemes.nord.gruvbox.normal]
# black = "#1d2021"
# blue = "#458588"
# cyan = "#689d6a"
# green = "#98971a"
# magenta = "#b16286"
# red = "#cc241d"
# white = "#a89984"
# yellow = "#d79921"
# 
# [schemes.nord.gruvbox.primary]
# background = "#1d2021"
# bright_foreground = "#f9f5d7"
# dim_foreground = "#f2e5bc"
# foreground = "#fbf1c7"
# 
# [schemes.nord.gruvbox.selection]
# background = "CellForeground"
# text = "CellBackground"
# 
# [schemes.nord.gruvbox.vi_mode_cursor]
# cursor = "CellForeground"
# text = "CellBackground"
# 
# [schemes.nord.normal]
# black = "#3b4252"
# blue = "#81a1c1"
# cyan = "#88c0d0"
# green = "#a3be8c"
# magenta = "#b48ead"
# red = "#bf616a"
# white = "#e5e9f0"
# yellow = "#ebcb8b"
# 
# [schemes.nord.primary]
# background = "#2e3440"
# dim_foreground = "#a5abb6"
# foreground = "#d8dee9"
# 
# [schemes.nord.search.footer_bar]
# background = "#434c5e"
# foreground = "#d8dee9"
# 
# [schemes.nord.search.matches]
# background = "#88c0d0"
# foreground = "CellBackground"
# 
# [schemes.nord.selection]
# background = "#4c566a"
# text = "CellForeground"
# 
# [schemes.nord.vi_mode_cursor]
# cursor = "#d8dee9"
# text = "#2e3440"
# 
# [schemes.solarized.bright]
# black = "0x657b83"
# blue = "0x839496"
# cyan = "0x93a1a1"
# green = "0x586e75"
# magenta = "0x6c71c4"
# red = "0xcb4b16"
# white = "0xfdf6e3"
# yellow = "0x657b83"
# 
# [schemes.solarized.normal]
# black = "0x073642"
# blue = "0x268bd2"
# cyan = "0x2aa198"
# green = "0x859900"
# magenta = "0xd33682"
# red = "0xdc322f"
# white = "0xeee8d5"
# yellow = "0xb58900"
# 
# [schemes.solarized.primary]
# background = "0x002b36"
# foreground = "0x839496"
